# Generated by Django 4.1.3 on 2022-12-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='enddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='startdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
